### ISSUE TITLE
No way to exclude files/methods

### ISSUE THREAD

**Issue by westlakem** [seattlerb/flog#62]
We have some code that just has to be complex and would like a way to mark those files or methods to ignore.  Something like the [config.reek](https://github.com/troessner/reek#configuration-file) file that can be used with [rubycritic](https://github.com/whitesmith/rubycritic).

**Comment by zenspider** [comment]
You can already ignore files because flog uses https://github.com/seattlerb/path_expander for cmdline processing.

I'm experimenting with a tree-oriented pattern matching extension to sexp_processor that will allow filtering at the sexp level. This will allow you to filter methods (or whatever you want to filter). It is already in beta in flay on codeclimate, but isn't finalized or integrated into flog or anything else yet. I'd love feedback on how you think you'd like to do it.

**Comment by westlakem** [comment]
I cannot use that with rubycritic, as they have no way to pass the path_expander options to flog.

**Comment by karlwilbur** [comment]
@soumyaray You would use `-/path/to/file/or.*.glob` 

See: https://github.com/seattlerb/path_expander/blob/master/lib/path_expander.rb#L68-L80

**Comment by zenspider** [comment]
I'm going to close this. The solution exists as I pointed out 2 years ago and @karlwilbur did again just now. This is the flog project, not rubycritic. So maybe an issue should be opened up over there if you can't pass things through.
